### ISSUE TITLE
Promise resolution never returned

### ISSUE THREAD

**Issue by cryptouru** [meanie/mongoose-upsert-many#1]
At the end of index.js the promise resolution is never returned, therefore is undefined when handling it outside of the upsertMany function. 

I managed to get the result by changing the code the following way:

```javascript
   return new Promise((resolve, reject) => {
      bulk.execute((error, result) => {
        if (error) {
          return reject(error);
        }
        return resolve(result);
      });
    });
```
I hope this helps. Cheers!

**Comment by adamreisnz** [comment]
Good catch, thanks. There's no need to `return resolve(result)`, but the promise itself should indeed be returned. I have made these changes 👍

**Comment by adamreisnz** [comment]
Released in 1.5.0, let me know if that works for you

**Comment by cryptouru** [comment]
Worked like a charm! You are welcome and thank you for the fine piece of code 💃

**Comment by adamreisnz** [comment]
Awesome, no worries!
