### ISSUE TITLE
 Not a true upsert?

### ISSUE THREAD

**Issue by bristles5** [meanie/mongoose-upsert-many#10]
I have a model that has default values.
```
employeeId: {
        type: String,
        required: true
    },
    isInvited: {
        type: Boolean,
        default: false
    },
    isNominee: {
        type: Boolean,
        default: false
    },
    isAttendee: {
        type: Boolean,
        default: false
    }
 ```
Upon initial upsertMany it creates a document with 
```
{
 employeeId: 1,
 isInvited: true
}
```
If i want to upsertMany again only make the isNominee true,
```
{
 employeeId: 1,
isNominee: true
}
```
The modelToObject makes an object like 
```
{
 employeeId:1,
 isInvited: false,
 isNominee:  true,
 isAttendee: false
}
```
This is incorrect behavior because I want to maintain the isInvited being true from the initial create. Any idea how to resolve this issue? The same thing happens for extra properties that may exist on initial create but are omitted from the upsert. If the object passed in does not contain the property then the upsert removes that property when it creates the new model from the modelToObject. 
ex... 
Initial Object in DB:
```
{
 shape: 'square',
color: 'Yellow',
text: 'Here'
}
```
OBJ to be updated:
```
{
  shape: 'square',
 color: 'Blue'
}
```
When your function is called the replaced document did not keep the text property from the original document

**Comment by adamreisnz** [comment]
Hi there, could you provide a standalone Node script that reproduces this behaviour? This will make it easier for me to analyse the problem and implement a fix.

**Comment by z0marlin** [comment]
Any updates on this? Facing the same issue.

**Comment by adamreisnz** [comment]
As per the last comment. Could you provide a standalone Node script that reproduces this behaviour? This will make it easier for me to analyse the problem and implement a fix

**Comment by z0marlin** [comment]
Sorry for the late reply. Here is a standalone script.
```js
const mongoose = require('mongoose');
const mup = require('@meanie/mongoose-upsert-many');
const { Schema } = mongoose;

const demoSchema = new Schema({
  field1: String,
  field2: {
    default: 'hello',
    type: String
  },
  field3: Number
});

demoSchema.plugin(mup);

const demoModel = mongoose.model('Demo', demoSchema);

async function demonstrateIssue() {
  // Connection part skipped

  // Sample doc. Note that the value of field2 is explicitly provided.
  var newDoc = new demoModel({
    field1: "abc",
    field2: "xyz",
    field3: 11
  });
  await newDoc.save();

  // items to be updated.
  const items = [{
    field1: "abc",
    field3: 5
  }];
  const mf = ["field1"];

  // Expected behaviour - Update field1 and field3 of all
  // documents using field1 as the matching criteria.
  const res = await demoModel.upsertMany(items, mf);
}
```

**Comment by adamreisnz** [comment]
Ok I see what you mean now, I have asked on the progress of https://github.com/Automattic/mongoose/issues/8271 which will resolve this issue once it lands.

**Comment by adamreisnz** [comment]
Fixed for now, allowing you to bypass the model conversion using the schema setting `upsertEnsureModel: false`. The default of this setting will remain `true`, because sometimes you want to have default values, like a timestamp.

I've also added a `upsertNoDefaults` config setting, which will only be available once https://github.com/Automattic/mongoose/issues/8271 is implemented.
