### ISSUE TITLE
Add the option to use $set

### ISSUE THREAD

**Issue by raydaim** [meanie/mongoose-upsert-many#11]
I have a use case where I need to upsert just some fields of the document the solution would be to add $set operator to the replaceOne 

`        bulk
          .find(match)
          .upsert()
          .replaceOne({$set:item});`

**Comment by adamreisnz** [comment]
Hi, thanks for your PR. However, can you please clarify how `$set` is to be used with `replaceOne`. I can't find any information about it in the MongoDB docs:

https://docs.mongodb.com/manual/reference/method/Bulk.find.replaceOne/#Bulk.find.replaceOne

In fact, the documentation explicitly mentions: `Contains only field and value pairs.` That implies no operators.

**Comment by raydaim** [comment]
@adamreisnz : Yes I agree, my bad 😓 in this case we can use updateOne instead of replaceOne  it will create the field if it does not exist otherwise it wont replace the whole document every time https://docs.mongodb.com/manual/reference/method/Bulk.find.updateOne/

**Comment by adamreisnz** [comment]
Right, so are you suggesting that `updateOne` can be used from this plugin (with `$set`)?

**Comment by raydaim** [comment]
Yes in case we need to update some fields only of the original document , instead of overriding the whole document

**Comment by adamreisnz** [comment]
Ok, is there a reason that you cannot simply use `updateMany` if you are updating fields?

This package was explicitly designed to offer a plugin to do an upsert operation, that means replacing the existing document if it already exists. To update many documents in one go is probably beyond the scope of this package, as you can use native mongoose functions for that.

I might be missing something though, so feel free to let me know if you think we should change this package.

**Comment by adamreisnz** [comment]
@raydaim is this still relevant?

**Comment by raydaim** [comment]
@adamreisnz the problem with update many is that we have to specify the search criteria / the new values for all the document, In my use case I want to create the document if it does not exist, update its values with the ones supplied in the query if it exists while keeping the attributes that I did not supplie in my query for exemple:

```
oldDoc:{
    ID: 1,
    a:1,
    b:2,
    c:3
    }

queryDoc:{
    ID:1,
    a:5,
    b:6
    }
expectedResultDoc:{
    ID:1,
    a:5,
    b:6,
    c:3
}
```
as you can see here we are keeping the old value of c.

**Comment by adamreisnz** [comment]
I think the new 2.0.0 will provide what you need, as the plugin will now use `updateOne` as the bulk op by default, instead of `replaceOne`. This should allow you to update specific fields of the item. See readme for details.

**Comment by adamreisnz** [comment]
Let me know if that works for you. I don't think `$set` is supported in `bulkWrite`, but it should do what you're after.

**Comment by raydaim** [comment]
> Let me know if that works for you. I don't think `$set` is supported in `bulkWrite`, but it should do what you're after.

@adamreisnz : from what I see here it is supported https://docs.mongodb.com/manual/reference/method/db.collection.bulkWrite

Thank you so much for these updates, the version 2.0.0 adds more flexibility to the library. 

I am currently using a customised version of the v1 with this small modification 
```
       bulk
          .find(match)
          .upsert()
          .updateOne({
            $set: { ...item, updatedAt: new Date() },
            $setOnInsert: { createdAt: new Date() }
          });
```
I am forcing the updated at and the created at because they are not created automatically which is weird but it is working perfectly for me.
However I will try to test the v2 and see if it works 😉
