### ISSUE TITLE
Not running Mongoose validations?

### ISSUE THREAD

**Issue by coatesap** [meanie/mongoose-upsert-many#14]
Hi, thanks for a very useful plugin. Could you confirm though whether this is bypassing the usual Mongoose validations (eg. for required fields) by using `bulkWrite`?

**Comment by zaidkazi** [comment]
Please set the `ensureModel` flag as **true** the default is **false** which will skip validation.

**Comment by coatesap** [comment]
The ‘ensureModel’ flag will create a Mongoose model instance (in order to set default values), but as far as I’m aware, this doesn’t run validations, as these usually happen as part of pre-save middleware (which seems to be bypassed when using bulkWrite)...

**Comment by adamreisnz** [comment]
Hi @coatesap, yes I can confirm that the plugin uses `bulkWrite` under the hood, so it will bypass the usual pre-save hooks and validation, but with the `ensureModel` flag, you can opt-in to have your data at least be initialised with default values.

For this major version we opted to turn this off by default, to allow the most flexibility and control of your data.

**Comment by coatesap** [comment]
Ok, thanks for confirming that. It would be useful to mention this limitation in the readme.
