### ISSUE TITLE
Await throws error 'await is only valid in async function'

### ISSUE THREAD

**Issue by DjovDev** [meanie/mongoose-upsert-many#16]
Hello, is it possible to integrate traditional callback support forf this plugin?

Await does not work for me for some reason:

**SyntaxError: await is only valid in async function**

```
    const mongoose = require('mongoose');

    //Upsert many mongoose plugin
    const upsertMany = require('@meanie/mongoose-upsert-many');
    mongoose.plugin(upsertMany);
    
    var localPartnumber = require(__dirname + '/models/localPartNumber')
    var data = [...] //retrieved from FTP
    console.log('Processing ' + data.length + ' lines to database')
    const upsertConfig = {matchFields: ['code', 'shop']};

    //not async for some reason
    var processedPartNos = await localPartnumber.upsertMany(data, upsertConfig)
```

**Comment by DjovDev** [comment]
Removing "var processedPartNos = await " part of the code works as expected. Parts are being upserted correctly, I would just like some feedback from the function about the inserted/updated quantities for logging.

**Comment by adamreisnz** [comment]
You need to use the `await` call in a function that is `async`, e.g.:

```js
async function myFunction() {
  //do stuff...
  const processedPartNos = await localPartnumber.upsertMany(data, upsertConfig);
}
```

Otherwise, just use regular promises:

```js
localPartnumber
  .upsertMany(data, upsertConfig)
  .then(() => ...);
```

No plans to add callback support. You can either use promises or async/await. The Node community is kind of moving away from callbacks.

**Comment by DjovDev** [comment]
Awesome, thanks a lot man 👍
