### ISSUE TITLE
Is there a way to retrieve the results of the operation?

### ISSUE THREAD

**Issue by cromieent** [meanie/mongoose-upsert-many#3]
I don't see this documented, but the object that is returned just contains the number of objects affected (i.e. updates or inserts) and doesn't return the new versions of the documents that were affected.  Is this by design or is it something we should be expecting in a new version of this plugin?

**Comment by adamreisnz** [comment]
Hi there, [what we return](https://github.com/meanie/mongoose-upsert-many/blob/master/index.js#L40-L48) is exactly what comes back from the underlying [`bulk.execute`](https://docs.mongodb.com/manual/reference/method/Bulk.execute/) call.

I don't think that returns the new versions of the documents that were affected, you'd need to run another query afterwards to obtain them.

Let me know if that clarifies!

**Comment by rohit-appdirect** [comment]
How can I call callback function from here?
//Add new Product
module.exports.addBulkProducts = function(products, callback){
	const matchFields = ['itemno'];
	Products.upsertMany(products, matchFields);
}

**Comment by adamreisnz** [comment]
You may want to look at [bulkWrite](https://mongoosejs.com/docs/api.html#model_Model.bulkWrite) instead, I think we'll be moving to use that instead of the older bulk approach.

But once installed, upsertMany will be available on your model, so:

```js
await mongoose
  .model('Products')
  .upsertMany(products, matchFields);
```
