### ISSUE TITLE
Is it possible to skip particular field to update

### ISSUE THREAD

**Issue by rohitdhore** [meanie/mongoose-upsert-many#7]
If I have specific field which I don't want to update if document already exists.
Can I do that with current code and how?

Lets Items say schema has following fields:
item_id: <auto generated for every product every time>
name: string
price: Number
tax: Number
item_code: String

const items = [{item_id: "item_1234_9878", name: "item 1", price: 2000, tax: 18, item_code: "code_CSVN"},{item_id: "item_1235_9878", name: "item 2", price: 3000, tax: 18, item_code: "code_MXPL"}]

const matchFields = ['itemno'];

//Now Item 1 already exists matched by itemno and I want to update all other fields but not the item_id
//{item_id: "item_1111_9878", name: "item 1", price: 2000, tax: 18, item_code: "code_CSVN"}

const result = await Items.upsertMany(items, matchFields);

**Comment by adamreisnz** [comment]
Shouldn't the item ID be the same value as the existing documents?
In that case you shouldn't worry, and MongoDB won't update it.

Otherwise, since the item ID is not needed for matching, just remove it from your data prior to passing it to `upsertMany` and it won't be updated.

E.g.
```js
items.forEach(item => delete item.item_id);
```

**Comment by bencbaumann** [comment]
Is there a way to filter on the non id fields? For example, you want to skip over price and update the rest of the fields.

**Comment by adamreisnz** [comment]
As above, just remove the data you don't want to update prior to passing it to `upsertMany`

**Comment by bencbaumann** [comment]
Thank you @adamreisnz
